### ISSUE TITLE
Bug in MHA

### ISSUE THREAD

**Issue by henrycharlesworth91** [gazelle93/Transformer-Various-Positional-Encoding#1]
Hi, I think there is a bug in the MHA implementation.

If we have the output of:
`output, attn_score = self.relative_scaled_dot_attn(query, key, value, a_key, a_value, mask)`

this is [B * NH, T, HD] (B - batch, NH - num heads, T - timestep, HD - head dim).

Line 189 of attentions.py then does:

```
output = output.view(self.num_heads, batch_size, -1, self.head_dim)
output = self.reshape_to_concat(batch_size, output)
```

But in the implementation of reshape_to_concat:

```
    def reshape_to_concat(self, batch_size, _tensor):
        # before shape: (batch size, number of heads, input length, head dimension)
        # after shape: (batch size, input length, number of heads, head dimension)
        _tensor = _tensor.permute(0, 2, 1, 3)
        return _tensor.contiguous().view(batch_size, -1, self.num_heads * self.head_dim)
```

Here we're actually passing in [NH, B, T, HD], rather than [N, NH, T, HD].

This then gets permuted tp [NH, T, B, HD] before being reshaped, which is wrong because we obviously want the tensor to be [B, T, NH, HD] here.

**Comment by gazelle93** [comment]
Hi @henrycharlesworth91!
Thank you very much for your comments.
First of all, yes you are right! The order of the tensor passed to the 'reshape_ro_concat' is [NH, B, T, HD], rather than [B, NH, T, HD]. I'll reflect on it in the comment.
Also, as you mentioned the permute has to be in the order of [B, T, NH, HD] rather than [NH, T, B, HD]. I'll also reflect on it right away.
Once again, thank you very much for your comments!
